-- dropDDL.sql
-- UMBC Parking Management System Reset Script

DROP TABLE IF EXISTS Payments CASCADE;
DROP TABLE IF EXISTS Tickets CASCADE;
DROP TABLE IF EXISTS SensorEvents CASCADE;
DROP TABLE IF EXISTS Sensors CASCADE;
DROP TABLE IF EXISTS Reservations CASCADE;
DROP TABLE IF EXISTS Spots CASCADE;
DROP TABLE IF EXISTS Lots CASCADE;
DROP TABLE IF EXISTS Permits CASCADE;
DROP TABLE IF EXISTS PermitTypes CASCADE;
DROP TABLE IF EXISTS User_Vehicles CASCADE;
DROP TABLE IF EXISTS Vehicles CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Roles CASCADE;